import os
import torch
from io import BytesIO
from PIL import Image

# Setup singleton instance
_vqa_engine = None

# Prevent HuggingFace from hanging on Windows SSL issues
os.environ["HF_HUB_OFFLINE"] = "1"

class QwenVLMEngine:
    def __init__(self):
        print("[VQA] Initializing Qwen2-VL-2B-Instruct...")
        # Since this is a demo to run on 8GB RAM, we use bfloat16 and automatic device mapping.
        # Fallback gracefully if transformers/qwen_vl_utils are not installed for pure testing.
        self.model = None
        self.processor = None
        try:
            from transformers import Qwen2VLForConditionalGeneration, AutoProcessor
            self.model = Qwen2VLForConditionalGeneration.from_pretrained(
                "Qwen/Qwen2-VL-2B-Instruct",
                torch_dtype=torch.bfloat16,
                device_map="auto"
            )
            self.processor = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-2B-Instruct")
            print("[VQA] Qwen2-VL-2B-Instruct initialized successfully.")
        except ImportError as e:
            print(f"[VQA-WARN] Missing dependencies for Qwen2-VL: {e}. VQA will return mock answers.")
        except Exception as e:
            print(f"[VQA-WARN] Failed to load model: {e}. VQA will return mock answers.")

    def answer_question(self, image_bytes: bytes, question: str) -> str:
        """
        Receives an image as bytes and a natural language question.
        Returns the text answer generated by Qwen2-VL.
        """
        if self.model is None or self.processor is None:
            # Fallback mock for testing without GPU/dependencies
            return f"Mock answer: LLaVA/Qwen is offline. Question was '{question}'"

        try:
            from qwen_vl_utils import process_vision_info
            
            image = Image.open(BytesIO(image_bytes)).convert("RGB")
            
            messages = [
                {
                    "role": "user",
                    "content": [
                        {"type": "image", "image": image},
                        {"type": "text", "text": question}
                    ]
                }
            ]
            
            text = self.processor.apply_chat_template(
                messages, tokenize=False, add_generation_prompt=True
            )
            image_inputs, video_inputs = process_vision_info(messages)
            
            inputs = self.processor(
                text=[text],
                images=image_inputs,
                videos=video_inputs,
                padding=True,
                return_tensors="pt"
            ).to(self.model.device)
            
            generated_ids = self.model.generate(**inputs, max_new_tokens=128)
            generated_ids_trimmed = [
                out_ids[len(in_ids):] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
            ]
            
            output_text = self.processor.batch_decode(
                generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
            )
            
            return output_text[0].strip()
            
        except Exception as e:
            print(f"[VQA-ERROR] Inference failed: {e}")
            return "Error generating answer."

    def verify_image_match(self, image_bytes: bytes, query: str) -> bool:
        """
        Uses VQA to verify if the image matches the query.
        Returns True if it matches, False otherwise.
        """
        prompt = f"Does this image match the following description: '{query}'? Answer with exactly 'Yes' or 'No'."
        answer = self.answer_question(image_bytes, prompt).strip().lower()
        if answer.startswith("yes"):
            return True
        return False

def get_vqa_engine() -> QwenVLMEngine:
    global _vqa_engine
    if _vqa_engine is None:
        _vqa_engine = QwenVLMEngine()
    return _vqa_engine
